### ISSUE TITLE
This api must use premium account for login?

### ISSUE THREAD

**Issue by flixmu** [hyugogirubato/API-Crunchyroll-Beta#4]
I can login and get access token then i get signature, key pair id and policy. But i am using for `https://beta-api.crunchyroll.com/cms/v2/US/M3/crunchyroll/episodes/` cant work. i am using free account for login api.

**Comment by hyugogirubato** [comment]
@flixmu 
Mmm either the episode you loaded is not available in your region, or your request is wrong because the only time a premium account is required is when requesting video streams (for premium videos). All other requests can be made without needing an account (but still requires an access token)
